<a href="https://colab.research.google.com/github/aabyyaann/Practical-Linear-Algebra-for-Data-Science/blob/main/Chapter8_Matrix_Inverses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 8 — Matrix Inverses

## Tujuan Chapter
Pada chapter ini, kita mempelajari konsep **invers matriks** (*matrix inverse*) dalam aljabar linear menggunakan Python.  
Fokus pembahasan chapter ini meliputi:

1. pengertian matriks invers  
2. syarat suatu matriks memiliki invers  
3. menghitung invers matriks dengan NumPy  
4. memverifikasi sifat \( A A^{-1} = I \)  
5. memahami hubungan invers dengan penyelesaian sistem linear  
6. membandingkan penggunaan invers eksplisit vs `np.linalg.solve()`  
7. melihat kasus matriks singular yang tidak memiliki invers  

Chapter ini penting karena invers matriks sering muncul dalam:
- penyelesaian sistem persamaan linear
- transformasi linear
- regresi linear
- optimisasi
- machine learning

## Ringkasan Teori

### 1. Apa itu invers matriks?
Untuk sebuah matriks persegi \( A \), invers matriks ditulis sebagai \( A^{-1} \), yaitu matriks yang memenuhi:

\[
A A^{-1} = A^{-1} A = I
\]

dengan \( I \) adalah **identity matrix**.

Artinya, invers matriks berperan seperti kebalikan pada bilangan biasa:
- jika \( a \neq 0 \), maka \( a \cdot \frac{1}{a} = 1 \)
- jika \( A \) invertible, maka \( A A^{-1} = I \)

---

### 2. Kapan matriks punya invers?
Suatu matriks **hanya dapat memiliki invers jika**:
- matriksnya **persegi** (\( n \times n \))
- **determinannya tidak nol**
- rank penuh (*full rank*)
- kolom/barisnya saling independen linear

Jika determinan = 0, maka matriks disebut **singular** dan **tidak punya invers**.

---

### 3. Mengapa invers penting?
Jika kita punya sistem linear:

\[
A\mathbf{x} = \mathbf{b}
\]

dan \( A \) invertible, maka solusi bisa ditulis:

\[
\mathbf{x} = A^{-1}\mathbf{b}
\]

Walaupun secara teori benar, dalam praktik komputasi kita **lebih disarankan menggunakan** `np.linalg.solve(A,b)` daripada menghitung invers secara eksplisit, karena:
- lebih stabil secara numerik
- lebih efisien
- lebih cepat

---

### 4. Hubungan dengan identitas
Jika \( A^{-1} \) benar, maka:

\[
A A^{-1} = I
\]

dan hasilnya harus menjadi identity matrix.  
Karena komputer bekerja dengan bilangan floating point, hasil numerik kadang tidak persis 0 atau 1, tetapi sangat dekat.

---

### 5. Intuisi geometris
Jika sebuah matriks melakukan transformasi linear terhadap ruang, maka invers matriks adalah transformasi yang **membalikkan efek tersebut**.

Contoh:
- jika \( A \) meregangkan dan memutar vektor,
- maka \( A^{-1} \) akan mengembalikan vektor ke posisi semula.

In [1]:
# Import library utama
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, suppress=True)

## 1. Membuat matriks persegi

Kita mulai dengan sebuah matriks 2x2 sederhana yang memiliki invers.

In [2]:
A = np.array([
    [2, 1],
    [1, 1]
], dtype=float)

print("Matriks A:")
print(A)
print("Shape A:", A.shape)

Matriks A:
[[2. 1.]
 [1. 1.]]
Shape A: (2, 2)


## 2. Menghitung invers matriks dengan `np.linalg.inv()`

NumPy menyediakan fungsi `np.linalg.inv()` untuk menghitung invers matriks.

In [3]:
A_inv = np.linalg.inv(A)

print("Invers dari A:")
print(A_inv)

Invers dari A:
[[ 1. -1.]
 [-1.  2.]]


## 3. Verifikasi sifat invers

Jika invers benar, maka:

\[
A A^{-1} = I
\]

dan juga:

\[
A^{-1} A = I
\]

Kita cek keduanya.

In [4]:
left_product = A @ A_inv
right_product = A_inv @ A

print("A @ A_inv =")
print(left_product)

print("\nA_inv @ A =")
print(right_product)

A @ A_inv =
[[1. 0.]
 [0. 1.]]

A_inv @ A =
[[1. 0.]
 [0. 1.]]


## 4. Membandingkan dengan identity matrix

Hasil perkalian seharusnya sama dengan matriks identitas.

In [5]:
I = np.eye(A.shape[0])

print("Identity matrix I:")
print(I)

print("\nApakah A @ A_inv mendekati I?")
print(np.allclose(left_product, I))

print("\nApakah A_inv @ A mendekati I?")
print(np.allclose(right_product, I))

Identity matrix I:
[[1. 0.]
 [0. 1.]]

Apakah A @ A_inv mendekati I?
True

Apakah A_inv @ A mendekati I?
True


## Penjelasan
Fungsi `np.allclose()` digunakan karena hasil komputasi floating point sering tidak persis sama, tetapi sangat dekat.  
Jika hasil `True`, maka secara numerik perkalian tersebut dianggap sama dengan matriks identitas.

## 5. Contoh matriks 3x3

Sekarang kita coba matriks yang lebih besar.

In [6]:
B = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
], dtype=float)

print("Matriks B:")
print(B)

Matriks B:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]


In [7]:
B_inv = np.linalg.inv(B)

print("Invers matriks B:")
print(B_inv)

Invers matriks B:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [8]:
print("B @ B_inv =")
print(B @ B_inv)

print("\nApakah mendekati identity?")
print(np.allclose(B @ B_inv, np.eye(3)))

B @ B_inv =
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]

Apakah mendekati identity?
True


## 6. Determinan dan keberadaan invers

Salah satu cara paling umum untuk mengecek apakah matriks punya invers adalah melihat determinannya.

- Jika `det(A) != 0` → matriks invertible
- Jika `det(A) == 0` → matriks singular, tidak punya invers

In [9]:
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("det(A) =", det_A)
print("det(B) =", det_B)

det(A) = 1.0
det(B) = 0.9999999999999964


## 7. Contoh matriks singular

Sekarang kita buat matriks yang **tidak punya invers**.

In [10]:
C = np.array([
    [1, 2],
    [2, 4]
], dtype=float)

print("Matriks C:")
print(C)

print("\nDeterminan C:")
print(np.linalg.det(C))

Matriks C:
[[1. 2.]
 [2. 4.]]

Determinan C:
0.0


Perhatikan bahwa baris kedua merupakan kelipatan dari baris pertama.  
Artinya, matriks ini **tidak full rank** dan determinannya 0, sehingga matriks tersebut singular.

In [11]:
try:
    C_inv = np.linalg.inv(C)
    print(C_inv)
except np.linalg.LinAlgError as e:
    print("Error:", e)

Error: Singular matrix


## Penjelasan
Error di atas menunjukkan bahwa matriks singular tidak dapat diinverskan.  
Ini penting dalam machine learning dan komputasi numerik, karena matriks yang singular sering menyebabkan solusi tidak unik atau bahkan tidak bisa dihitung dengan metode tertentu.

# 8. Menggunakan invers untuk menyelesaikan sistem linear

Misalkan kita punya sistem:

\[
A\mathbf{x} = \mathbf{b}
\]

Jika \( A \) invertible, maka:

\[
\mathbf{x} = A^{-1}\mathbf{b}
\]

Mari kita coba dengan contoh sederhana.

In [12]:
A = np.array([
    [3, 1],
    [1, 2]
], dtype=float)

b = np.array([9, 8], dtype=float)

print("A =")
print(A)

print("\nb =")
print(b)

A =
[[3. 1.]
 [1. 2.]]

b =
[9. 8.]


In [13]:
A_inv = np.linalg.inv(A)
x_via_inverse = A_inv @ b

print("Solusi x menggunakan invers:")
print(x_via_inverse)

Solusi x menggunakan invers:
[2. 3.]


## 9. Verifikasi solusi

Kita cek apakah hasil \( x \) benar-benar memenuhi \( A x = b \).

In [14]:
check_b = A @ x_via_inverse

print("A @ x =")
print(check_b)

print("\nApakah sama dengan b?")
print(np.allclose(check_b, b))

A @ x =
[9. 8.]

Apakah sama dengan b?
True


# 10. Cara yang lebih baik: `np.linalg.solve()`

Walaupun rumus teorinya adalah:

\[
x = A^{-1}b
\]

dalam praktik komputasi, cara yang lebih baik adalah:

```python
np.linalg.solve(A, b)

In [15]:
x_via_solve = np.linalg.solve(A, b)

print("Solusi x menggunakan np.linalg.solve():")
print(x_via_solve)

Solusi x menggunakan np.linalg.solve():
[2. 3.]


In [16]:
print("Perbandingan hasil:")
print("x via inverse =", x_via_inverse)
print("x via solve   =", x_via_solve)

print("\nApakah keduanya sama?")
print(np.allclose(x_via_inverse, x_via_solve))

Perbandingan hasil:
x via inverse = [2. 3.]
x via solve   = [2. 3.]

Apakah keduanya sama?
True


## Penjelasan penting
Secara matematis, kedua pendekatan memberi hasil yang sama.  
Namun untuk aplikasi nyata, terutama matriks besar, **`np.linalg.solve()` lebih direkomendasikan** daripada menghitung invers lalu mengalikan dengan \( b \).

# 11. Visualisasi ide “transformasi lalu dibalik”

Secara geometris, matriks dapat dipandang sebagai transformasi linear.  
Jika sebuah vektor \( x \) ditransformasikan oleh matriks \( A \), maka:

\[
y = Ax
\]

Kemudian jika kita kalikan dengan inversnya:

\[
x = A^{-1}y
\]

vektor akan kembali ke posisi semula.

In [17]:
A = np.array([
    [2, 1],
    [1, 1]
], dtype=float)

A_inv = np.linalg.inv(A)

x = np.array([1, 2], dtype=float)
y = A @ x
x_recovered = A_inv @ y

print("x asli        =", x)
print("y = A @ x     =", y)
print("x dipulihkan  =", x_recovered)

x asli        = [1. 2.]
y = A @ x     = [4. 3.]
x dipulihkan  = [1. 2.]


In [18]:
A = np.array([
    [2, 1],
    [1, 1]
], dtype=float)

A_inv = np.linalg.inv(A)

x = np.array([1, 2], dtype=float)
y = A @ x
x_recovered = A_inv @ y

print("x asli        =", x)
print("y = A @ x     =", y)
print("x dipulihkan  =", x_recovered)

x asli        = [1. 2.]
y = A @ x     = [4. 3.]
x dipulihkan  = [1. 2.]


## Interpretasi visual
- **x asli** adalah vektor awal
- **y = A @ x** adalah hasil transformasi oleh matriks \( A \)
- **A_inv @ y** mengembalikan vektor ke posisi semula

Ini menunjukkan makna geometris dari invers: **membatalkan efek transformasi linear**.

In [19]:
D = np.diag([2, 4, 5])

print("Matriks diagonal D:")
print(D)

D_inv = np.linalg.inv(D)

print("\nInvers D:")
print(D_inv)

print("\nVerifikasi D @ D_inv:")
print(D @ D_inv)

Matriks diagonal D:
[[2 0 0]
 [0 4 0]
 [0 0 5]]

Invers D:
[[0.5  0.   0.  ]
 [0.   0.25 0.  ]
 [0.   0.   0.2 ]]

Verifikasi D @ D_inv:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 13. Hubungan invers dengan rank

Matriks yang invertible harus memiliki:
- rank penuh
- determinan tidak nol
- kolom independen linear
- baris independen linear

Mari kita bandingkan matriks invertible dan singular.

In [20]:
M1 = np.array([
    [1, 2],
    [3, 4]
], dtype=float)

M2 = np.array([
    [1, 2],
    [2, 4]
], dtype=float)

print("Rank M1 =", np.linalg.matrix_rank(M1))
print("det(M1) =", np.linalg.det(M1))

print("\nRank M2 =", np.linalg.matrix_rank(M2))
print("det(M2) =", np.linalg.det(M2))

Rank M1 = 2
det(M1) = -2.0000000000000004

Rank M2 = 1
det(M2) = 0.0


## Interpretasi
- `M1` memiliki rank penuh (2), sehingga invertible
- `M2` hanya rank 1, sehingga singular dan tidak punya invers

Ini memperlihatkan hubungan erat antara:
- rank
- determinan
- independensi linear
- keberadaan invers

# 14. Contoh numerik yang sedikit lebih realistis

Kita buat sistem linear 3 variabel dan selesaikan dengan dua cara:
1. menggunakan invers
2. menggunakan `np.linalg.solve()`

In [21]:
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
], dtype=float)

b = np.array([8, -11, -3], dtype=float)

print("A =")
print(A)
print("\nb =", b)

A =
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

b = [  8. -11.  -3.]


In [22]:
x_inv = np.linalg.inv(A) @ b
x_solve = np.linalg.solve(A, b)

print("x dengan invers:")
print(x_inv)

print("\nx dengan solve:")
print(x_solve)

x dengan invers:
[ 2.  3. -1.]

x dengan solve:
[ 2.  3. -1.]


In [23]:
print("Verifikasi A @ x_inv:")
print(A @ x_inv)

print("\nVerifikasi A @ x_solve:")
print(A @ x_solve)

Verifikasi A @ x_inv:
[  8. -11.  -3.]

Verifikasi A @ x_solve:
[  8. -11.  -3.]


# 15. Kelemahan menghitung invers secara eksplisit

Walaupun secara teori mudah dipahami, menghitung invers secara eksplisit punya beberapa kelemahan:

1. **lebih mahal secara komputasi**
2. **kurang stabil secara numerik**
3. bisa memperbesar error floating point
4. tidak diperlukan jika tujuan hanya menyelesaikan sistem linear

Karena itu:
- untuk teori → invers sangat penting
- untuk implementasi numerik → `solve()` biasanya lebih baik

# 16. Mini eksperimen: matriks acak invertible

Sekarang kita buat beberapa matriks acak dan memeriksa apakah:
- determinannya tidak nol
- hasil \( A A^{-1} \) mendekati identitas

In [24]:
np.random.seed(42)

for i in range(3):
    M = np.random.randn(3, 3)

    # pastikan tidak singular secara numerik
    if abs(np.linalg.det(M)) < 1e-8:
        print(f"Matriks ke-{i+1} terlalu dekat singular, dilewati")
        continue

    M_inv = np.linalg.inv(M)
    product = M @ M_inv

    print(f"\n=== Matriks ke-{i+1} ===")
    print("det(M) =", np.linalg.det(M))
    print("Apakah M @ M_inv mendekati I?", np.allclose(product, np.eye(3)))


=== Matriks ke-1 ===
det(M) = 1.0926527686175935
Apakah M @ M_inv mendekati I? True

=== Matriks ke-2 ===
det(M) = -1.0731492439897026
Apakah M @ M_inv mendekati I? True

=== Matriks ke-3 ===
det(M) = -0.7841349480349399
Apakah M @ M_inv mendekati I? True


# 17. Analisis hasil chapter

Dari seluruh percobaan pada chapter ini, kita bisa melihat beberapa poin penting:

### A. Invers hanya berlaku untuk matriks persegi yang invertible
Matriks harus:
- persegi
- rank penuh
- determinan tidak nol

### B. Invers membatalkan transformasi
Jika \( y = Ax \), maka \( x = A^{-1}y \).

### C. Invers dapat digunakan untuk menyelesaikan sistem linear
Jika \( A x = b \), maka solusi teoritisnya adalah:

\[
x = A^{-1}b
\]

### D. Dalam praktik, `solve()` lebih baik daripada `inv() @ b`
Karena:
- lebih cepat
- lebih stabil
- lebih efisien

### E. Matriks singular tidak punya invers
Jika determinan nol atau rank tidak penuh, maka invers tidak ada.

# Kesimpulan Chapter 8

Pada chapter ini, kita mempelajari konsep **matrix inverse** sebagai salah satu fondasi penting dalam aljabar linear.

## Poin utama yang dipelajari:
1. invers matriks \( A^{-1} \) adalah matriks yang memenuhi \( A A^{-1} = I \)
2. hanya matriks persegi dengan determinan tidak nol yang memiliki invers
3. invers dapat digunakan untuk menyelesaikan sistem linear \( Ax=b \)
4. matriks singular tidak dapat diinverskan
5. secara komputasi, `np.linalg.solve()` lebih baik daripada menghitung invers eksplisit
6. invers juga memiliki makna geometris sebagai transformasi yang membalikkan efek transformasi sebelumnya

## Relevansi ke machine learning dan deep learning
Konsep invers matriks penting dalam:
- normal equation pada regresi linear
- optimisasi numerik
- transformasi fitur
- dekomposisi matriks
- statistik multivariat
- pemodelan berbasis least squares

Dengan memahami invers matriks, kita memiliki fondasi kuat untuk chapter-chapter selanjutnya seperti:
- orthogonal matrices dan QR decomposition
- row reduction dan LU decomposition
- least squares
- eigendecomposition
- singular value decomposition (SVD)